/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.benzinga.BZClient.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * Chamber - Chamber
 */
public enum Chamber {
    HOUSE("House"),
    SENATE("Senate");

    @JsonValue
    private final String value;

    private Chamber(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
