/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.benzinga.BZClient.models.operations;

import org.benzinga.BZClient.utils.Utils;

public class GetDividendsV22RequestBuilder {

    private GetDividendsV22Request request;
    private final SDKMethodInterfaces.MethodCallGetDividendsV22 sdk;

    public GetDividendsV22RequestBuilder(SDKMethodInterfaces.MethodCallGetDividendsV22 sdk) {
        this.sdk = sdk;
    }

    public GetDividendsV22RequestBuilder request(GetDividendsV22Request request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetDividendsV22Response call() throws Exception {

        return sdk.getV22(
            request);
    }
}
