/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.benzinga.BZClient.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;
import java.util.Optional;

/**
 * GetEventsQueryParamParametersImportance - Importance
 */
public enum GetEventsQueryParamParametersImportance {
    ZERO(0L),
    ONE(1L),
    TWO(2L),
    THREE(3L),
    FOUR(4L),
    FIVE(5L);

    @JsonValue
    private final long value;

    private GetEventsQueryParamParametersImportance(long value) {
        this.value = value;
    }
    
    public long value() {
        return value;
    }
    
    public static Optional<GetEventsQueryParamParametersImportance> fromValue(long value) {
        for (GetEventsQueryParamParametersImportance o: GetEventsQueryParamParametersImportance.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
