/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.benzinga.BZClient.models.operations;

import org.benzinga.BZClient.utils.Utils;

public class GetGovernmentTradesRequestBuilder {

    private GetGovernmentTradesRequest request;
    private final SDKMethodInterfaces.MethodCallGetGovernmentTrades sdk;

    public GetGovernmentTradesRequestBuilder(SDKMethodInterfaces.MethodCallGetGovernmentTrades sdk) {
        this.sdk = sdk;
    }

    public GetGovernmentTradesRequestBuilder request(GetGovernmentTradesRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetGovernmentTradesResponse call() throws Exception {

        return sdk.get(
            request);
    }
}
