/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.benzinga.BZClient.models.operations;

import org.benzinga.BZClient.utils.Utils;

public class GetInsiderTransactionRequestBuilder {

    private GetInsiderTransactionRequest request;
    private final SDKMethodInterfaces.MethodCallGetInsiderTransaction sdk;

    public GetInsiderTransactionRequestBuilder(SDKMethodInterfaces.MethodCallGetInsiderTransaction sdk) {
        this.sdk = sdk;
    }

    public GetInsiderTransactionRequestBuilder request(GetInsiderTransactionRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetInsiderTransactionResponse call() throws Exception {

        return sdk.get(
            request);
    }
}
