/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.benzinga.BZClient.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;
import org.benzinga.BZClient.models.components.ModelsIPOJSON;
import org.benzinga.BZClient.utils.Response;
import org.benzinga.BZClient.utils.Utils;


public class GetIposV2Response implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * IPOs
     */
    private Optional<? extends ModelsIPOJSON> modelsIPOJSON;

    private Optional<? extends byte[]> body;

    @JsonCreator
    public GetIposV2Response(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends ModelsIPOJSON> modelsIPOJSON,
            Optional<? extends byte[]> body) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(modelsIPOJSON, "modelsIPOJSON");
        Utils.checkNotNull(body, "body");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.modelsIPOJSON = modelsIPOJSON;
        this.body = body;
    }
    
    public GetIposV2Response(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty(), Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * IPOs
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<ModelsIPOJSON> modelsIPOJSON() {
        return (Optional<ModelsIPOJSON>) modelsIPOJSON;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<byte[]> body() {
        return (Optional<byte[]>) body;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public GetIposV2Response withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GetIposV2Response withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetIposV2Response withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * IPOs
     */
    public GetIposV2Response withModelsIPOJSON(ModelsIPOJSON modelsIPOJSON) {
        Utils.checkNotNull(modelsIPOJSON, "modelsIPOJSON");
        this.modelsIPOJSON = Optional.ofNullable(modelsIPOJSON);
        return this;
    }

    /**
     * IPOs
     */
    public GetIposV2Response withModelsIPOJSON(Optional<? extends ModelsIPOJSON> modelsIPOJSON) {
        Utils.checkNotNull(modelsIPOJSON, "modelsIPOJSON");
        this.modelsIPOJSON = modelsIPOJSON;
        return this;
    }

    public GetIposV2Response withBody(byte[] body) {
        Utils.checkNotNull(body, "body");
        this.body = Optional.ofNullable(body);
        return this;
    }

    public GetIposV2Response withBody(Optional<? extends byte[]> body) {
        Utils.checkNotNull(body, "body");
        this.body = body;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetIposV2Response other = (GetIposV2Response) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.modelsIPOJSON, other.modelsIPOJSON) &&
            Objects.deepEquals(this.body, other.body);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            modelsIPOJSON,
            body);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetIposV2Response.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "modelsIPOJSON", modelsIPOJSON,
                "body", body);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends ModelsIPOJSON> modelsIPOJSON = Optional.empty();
 
        private Optional<? extends byte[]> body = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * IPOs
         */
        public Builder modelsIPOJSON(ModelsIPOJSON modelsIPOJSON) {
            Utils.checkNotNull(modelsIPOJSON, "modelsIPOJSON");
            this.modelsIPOJSON = Optional.ofNullable(modelsIPOJSON);
            return this;
        }

        /**
         * IPOs
         */
        public Builder modelsIPOJSON(Optional<? extends ModelsIPOJSON> modelsIPOJSON) {
            Utils.checkNotNull(modelsIPOJSON, "modelsIPOJSON");
            this.modelsIPOJSON = modelsIPOJSON;
            return this;
        }

        public Builder body(byte[] body) {
            Utils.checkNotNull(body, "body");
            this.body = Optional.ofNullable(body);
            return this;
        }

        public Builder body(Optional<? extends byte[]> body) {
            Utils.checkNotNull(body, "body");
            this.body = body;
            return this;
        }
        
        public GetIposV2Response build() {
            return new GetIposV2Response(
                contentType,
                statusCode,
                rawResponse,
                modelsIPOJSON,
                body);
        }
    }
}

