/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.benzinga.BZClient.models.operations;

import org.benzinga.BZClient.utils.Utils;

public class GetInsiderTransactionOwnerRequestBuilder {

    private GetInsiderTransactionOwnerRequest request;
    private final SDKMethodInterfaces.MethodCallGetInsiderTransactionOwner sdk;

    public GetInsiderTransactionOwnerRequestBuilder(SDKMethodInterfaces.MethodCallGetInsiderTransactionOwner sdk) {
        this.sdk = sdk;
    }

    public GetInsiderTransactionOwnerRequestBuilder request(GetInsiderTransactionOwnerRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetInsiderTransactionOwnerResponse call() throws Exception {

        return sdk.getOwner(
            request);
    }
}
