/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.benzinga.BZClient.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * GetMaQueryParamParametersDateSort - Sort by date
 */
public enum GetMaQueryParamParametersDateSort {
    EXPECTED("expected"),
    COMPLETED("completed"),
    ANNOUNCED("announced");

    @JsonValue
    private final String value;

    private GetMaQueryParamParametersDateSort(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
