/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.benzinga.BZClient.models.operations;

import org.benzinga.BZClient.utils.Utils;

public class GetNewsquantifiedDataRequestBuilder {

    private GetNewsquantifiedDataRequest request;
    private final SDKMethodInterfaces.MethodCallGetNewsquantifiedData sdk;

    public GetNewsquantifiedDataRequestBuilder(SDKMethodInterfaces.MethodCallGetNewsquantifiedData sdk) {
        this.sdk = sdk;
    }

    public GetNewsquantifiedDataRequestBuilder request(GetNewsquantifiedDataRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetNewsquantifiedDataResponse call() throws Exception {

        return sdk.get(
            request);
    }
}
