/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.benzinga.BZClient.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import org.benzinga.BZClient.utils.SpeakeasyMetadata;
import org.benzinga.BZClient.utils.Utils;


public class GetRemovedNewsRequest {

    /**
     * Updated Since
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=updatedSince")
    private Optional<String> updatedSince;

    /**
     * Page Size
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=pageSize")
    private Optional<Long> pageSize;

    /**
     * Page
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page")
    private Optional<Long> page;

    @JsonCreator
    public GetRemovedNewsRequest(
            Optional<String> updatedSince,
            Optional<Long> pageSize,
            Optional<Long> page) {
        Utils.checkNotNull(updatedSince, "updatedSince");
        Utils.checkNotNull(pageSize, "pageSize");
        Utils.checkNotNull(page, "page");
        this.updatedSince = updatedSince;
        this.pageSize = pageSize;
        this.page = page;
    }
    
    public GetRemovedNewsRequest() {
        this(Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * Updated Since
     */
    @JsonIgnore
    public Optional<String> updatedSince() {
        return updatedSince;
    }

    /**
     * Page Size
     */
    @JsonIgnore
    public Optional<Long> pageSize() {
        return pageSize;
    }

    /**
     * Page
     */
    @JsonIgnore
    public Optional<Long> page() {
        return page;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Updated Since
     */
    public GetRemovedNewsRequest withUpdatedSince(String updatedSince) {
        Utils.checkNotNull(updatedSince, "updatedSince");
        this.updatedSince = Optional.ofNullable(updatedSince);
        return this;
    }

    /**
     * Updated Since
     */
    public GetRemovedNewsRequest withUpdatedSince(Optional<String> updatedSince) {
        Utils.checkNotNull(updatedSince, "updatedSince");
        this.updatedSince = updatedSince;
        return this;
    }

    /**
     * Page Size
     */
    public GetRemovedNewsRequest withPageSize(long pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = Optional.ofNullable(pageSize);
        return this;
    }

    /**
     * Page Size
     */
    public GetRemovedNewsRequest withPageSize(Optional<Long> pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = pageSize;
        return this;
    }

    /**
     * Page
     */
    public GetRemovedNewsRequest withPage(long page) {
        Utils.checkNotNull(page, "page");
        this.page = Optional.ofNullable(page);
        return this;
    }

    /**
     * Page
     */
    public GetRemovedNewsRequest withPage(Optional<Long> page) {
        Utils.checkNotNull(page, "page");
        this.page = page;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetRemovedNewsRequest other = (GetRemovedNewsRequest) o;
        return 
            Objects.deepEquals(this.updatedSince, other.updatedSince) &&
            Objects.deepEquals(this.pageSize, other.pageSize) &&
            Objects.deepEquals(this.page, other.page);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            updatedSince,
            pageSize,
            page);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetRemovedNewsRequest.class,
                "updatedSince", updatedSince,
                "pageSize", pageSize,
                "page", page);
    }
    
    public final static class Builder {
 
        private Optional<String> updatedSince = Optional.empty();
 
        private Optional<Long> pageSize = Optional.empty();
 
        private Optional<Long> page = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Updated Since
         */
        public Builder updatedSince(String updatedSince) {
            Utils.checkNotNull(updatedSince, "updatedSince");
            this.updatedSince = Optional.ofNullable(updatedSince);
            return this;
        }

        /**
         * Updated Since
         */
        public Builder updatedSince(Optional<String> updatedSince) {
            Utils.checkNotNull(updatedSince, "updatedSince");
            this.updatedSince = updatedSince;
            return this;
        }

        /**
         * Page Size
         */
        public Builder pageSize(long pageSize) {
            Utils.checkNotNull(pageSize, "pageSize");
            this.pageSize = Optional.ofNullable(pageSize);
            return this;
        }

        /**
         * Page Size
         */
        public Builder pageSize(Optional<Long> pageSize) {
            Utils.checkNotNull(pageSize, "pageSize");
            this.pageSize = pageSize;
            return this;
        }

        /**
         * Page
         */
        public Builder page(long page) {
            Utils.checkNotNull(page, "page");
            this.page = Optional.ofNullable(page);
            return this;
        }

        /**
         * Page
         */
        public Builder page(Optional<Long> page) {
            Utils.checkNotNull(page, "page");
            this.page = page;
            return this;
        }
        
        public GetRemovedNewsRequest build() {
            return new GetRemovedNewsRequest(
                updatedSince,
                pageSize,
                page);
        }
    }
}

