/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.benzinga.BZClient.models.operations;

import org.benzinga.BZClient.utils.Utils;

public class GetRatingsRequestBuilder {

    private GetRatingsRequest request;
    private final SDKMethodInterfaces.MethodCallGetRatings sdk;

    public GetRatingsRequestBuilder(SDKMethodInterfaces.MethodCallGetRatings sdk) {
        this.sdk = sdk;
    }

    public GetRatingsRequestBuilder request(GetRatingsRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetRatingsResponse call() throws Exception {

        return sdk.get(
            request);
    }
}
