/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.benzinga.BZClient.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * ParametersDateSort - Date sort order
 */
public enum ParametersDateSort {
    ANNOUNCED(""announced""),
    EX(""ex""),
    PAYABLE(""payable""),
    RECORD(""record"");

    @JsonValue
    private final String value;

    private ParametersDateSort(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
