/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.benzinga.BZClient.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ParametersImportance - Importance
 */
public enum ParametersImportance {
    ZERO(0L),
    ONE(1L),
    TWO(2L),
    THREE(3L),
    FOUR(4L),
    FIVE(5L);

    private final long value;

    private ParametersImportance(long value) {
        this.value = value;
    }

    @JsonValue
    public long value() {
        return value;
    }
}
