/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.benzinga.BZClient.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * QueryParamDisplay - Display
 */
public enum QueryParamDisplay {
    FLAT("flat"),
    NESTED("nested");

    private final String value;

    private QueryParamDisplay(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return value;
    }
}
