/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.benzinga.BZClient.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * QueryParamSearchKeysType - Search keys type
 */
public enum QueryParamSearchKeysType {
    REPORT_ID("report_id"),
    TICKER("ticker");

    @JsonValue
    private final String value;

    private QueryParamSearchKeysType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<QueryParamSearchKeysType> fromValue(String value) {
        for (QueryParamSearchKeysType o: QueryParamSearchKeysType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
