/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.benzinga.bzclient.models.operations;


import com.benzinga.bzclient.models.components.ModelsAnalystInsightsJSON;
import com.benzinga.bzclient.utils.Response;
import com.benzinga.bzclient.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;


public class GetAnalystInsightsV1Response implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Analyst Insights
     */
    private Optional<? extends ModelsAnalystInsightsJSON> modelsAnalystInsightsJSON;

    @JsonCreator
    public GetAnalystInsightsV1Response(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends ModelsAnalystInsightsJSON> modelsAnalystInsightsJSON) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(modelsAnalystInsightsJSON, "modelsAnalystInsightsJSON");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.modelsAnalystInsightsJSON = modelsAnalystInsightsJSON;
    }
    
    public GetAnalystInsightsV1Response(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Analyst Insights
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<ModelsAnalystInsightsJSON> modelsAnalystInsightsJSON() {
        return (Optional<ModelsAnalystInsightsJSON>) modelsAnalystInsightsJSON;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public GetAnalystInsightsV1Response withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GetAnalystInsightsV1Response withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetAnalystInsightsV1Response withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Analyst Insights
     */
    public GetAnalystInsightsV1Response withModelsAnalystInsightsJSON(ModelsAnalystInsightsJSON modelsAnalystInsightsJSON) {
        Utils.checkNotNull(modelsAnalystInsightsJSON, "modelsAnalystInsightsJSON");
        this.modelsAnalystInsightsJSON = Optional.ofNullable(modelsAnalystInsightsJSON);
        return this;
    }

    /**
     * Analyst Insights
     */
    public GetAnalystInsightsV1Response withModelsAnalystInsightsJSON(Optional<? extends ModelsAnalystInsightsJSON> modelsAnalystInsightsJSON) {
        Utils.checkNotNull(modelsAnalystInsightsJSON, "modelsAnalystInsightsJSON");
        this.modelsAnalystInsightsJSON = modelsAnalystInsightsJSON;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetAnalystInsightsV1Response other = (GetAnalystInsightsV1Response) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.modelsAnalystInsightsJSON, other.modelsAnalystInsightsJSON);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            modelsAnalystInsightsJSON);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetAnalystInsightsV1Response.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "modelsAnalystInsightsJSON", modelsAnalystInsightsJSON);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends ModelsAnalystInsightsJSON> modelsAnalystInsightsJSON = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * Analyst Insights
         */
        public Builder modelsAnalystInsightsJSON(ModelsAnalystInsightsJSON modelsAnalystInsightsJSON) {
            Utils.checkNotNull(modelsAnalystInsightsJSON, "modelsAnalystInsightsJSON");
            this.modelsAnalystInsightsJSON = Optional.ofNullable(modelsAnalystInsightsJSON);
            return this;
        }

        /**
         * Analyst Insights
         */
        public Builder modelsAnalystInsightsJSON(Optional<? extends ModelsAnalystInsightsJSON> modelsAnalystInsightsJSON) {
            Utils.checkNotNull(modelsAnalystInsightsJSON, "modelsAnalystInsightsJSON");
            this.modelsAnalystInsightsJSON = modelsAnalystInsightsJSON;
            return this;
        }
        
        public GetAnalystInsightsV1Response build() {
            return new GetAnalystInsightsV1Response(
                contentType,
                statusCode,
                rawResponse,
                modelsAnalystInsightsJSON);
        }
    }
}

