/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.benzinga.bzclient.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * GetEarningsQueryParamParametersDateSort - Sort by date
 */
public enum GetEarningsQueryParamParametersDateSort {
    DATE("date");

    @JsonValue
    private final String value;

    private GetEarningsQueryParamParametersDateSort(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<GetEarningsQueryParamParametersDateSort> fromValue(String value) {
        for (GetEarningsQueryParamParametersDateSort o: GetEarningsQueryParamParametersDateSort.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
