/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.benzinga.bzclient.models.operations;

import com.benzinga.bzclient.utils.Options;
import com.benzinga.bzclient.utils.RetryConfig;
import com.benzinga.bzclient.utils.Utils;
import java.util.Optional;

public class GetInsiderTransactionOwnerRequestBuilder {

    private GetInsiderTransactionOwnerRequest request;
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKMethodInterfaces.MethodCallGetInsiderTransactionOwner sdk;

    public GetInsiderTransactionOwnerRequestBuilder(SDKMethodInterfaces.MethodCallGetInsiderTransactionOwner sdk) {
        this.sdk = sdk;
    }

    public GetInsiderTransactionOwnerRequestBuilder request(GetInsiderTransactionOwnerRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }
                
    public GetInsiderTransactionOwnerRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public GetInsiderTransactionOwnerRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }

    public GetInsiderTransactionOwnerResponse call() throws Exception {
        Optional<Options> options = Optional.of(Options.builder()
                                                    .retryConfig(retryConfig)
                                                    .build());
        return sdk.getOwner(
            request,
            options);
    }
}
