/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.benzinga.bzclient.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;
import java.util.Optional;

/**
 * GetMaQueryParamParametersImportance - Importance
 */
public enum GetMaQueryParamParametersImportance {
    ZERO(0L),
    ONE(1L),
    TWO(2L),
    THREE(3L),
    FOUR(4L),
    FIVE(5L);

    @JsonValue
    private final long value;

    private GetMaQueryParamParametersImportance(long value) {
        this.value = value;
    }
    
    public long value() {
        return value;
    }
    
    public static Optional<GetMaQueryParamParametersImportance> fromValue(long value) {
        for (GetMaQueryParamParametersImportance o: GetMaQueryParamParametersImportance.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
