/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.benzinga.bzclient.models.operations;


import com.benzinga.bzclient.models.components.HttpapiTrendingTickersListAPIResponse;
import com.benzinga.bzclient.utils.Response;
import com.benzinga.bzclient.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;


public class GetTickerTrendListDataResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * OK
     */
    private Optional<? extends HttpapiTrendingTickersListAPIResponse> httpapiTrendingTickersListAPIResponse;

    @JsonCreator
    public GetTickerTrendListDataResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends HttpapiTrendingTickersListAPIResponse> httpapiTrendingTickersListAPIResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(httpapiTrendingTickersListAPIResponse, "httpapiTrendingTickersListAPIResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.httpapiTrendingTickersListAPIResponse = httpapiTrendingTickersListAPIResponse;
    }
    
    public GetTickerTrendListDataResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * OK
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<HttpapiTrendingTickersListAPIResponse> httpapiTrendingTickersListAPIResponse() {
        return (Optional<HttpapiTrendingTickersListAPIResponse>) httpapiTrendingTickersListAPIResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public GetTickerTrendListDataResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GetTickerTrendListDataResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetTickerTrendListDataResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * OK
     */
    public GetTickerTrendListDataResponse withHttpapiTrendingTickersListAPIResponse(HttpapiTrendingTickersListAPIResponse httpapiTrendingTickersListAPIResponse) {
        Utils.checkNotNull(httpapiTrendingTickersListAPIResponse, "httpapiTrendingTickersListAPIResponse");
        this.httpapiTrendingTickersListAPIResponse = Optional.ofNullable(httpapiTrendingTickersListAPIResponse);
        return this;
    }

    /**
     * OK
     */
    public GetTickerTrendListDataResponse withHttpapiTrendingTickersListAPIResponse(Optional<? extends HttpapiTrendingTickersListAPIResponse> httpapiTrendingTickersListAPIResponse) {
        Utils.checkNotNull(httpapiTrendingTickersListAPIResponse, "httpapiTrendingTickersListAPIResponse");
        this.httpapiTrendingTickersListAPIResponse = httpapiTrendingTickersListAPIResponse;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetTickerTrendListDataResponse other = (GetTickerTrendListDataResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.httpapiTrendingTickersListAPIResponse, other.httpapiTrendingTickersListAPIResponse);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            httpapiTrendingTickersListAPIResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetTickerTrendListDataResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "httpapiTrendingTickersListAPIResponse", httpapiTrendingTickersListAPIResponse);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends HttpapiTrendingTickersListAPIResponse> httpapiTrendingTickersListAPIResponse = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * OK
         */
        public Builder httpapiTrendingTickersListAPIResponse(HttpapiTrendingTickersListAPIResponse httpapiTrendingTickersListAPIResponse) {
            Utils.checkNotNull(httpapiTrendingTickersListAPIResponse, "httpapiTrendingTickersListAPIResponse");
            this.httpapiTrendingTickersListAPIResponse = Optional.ofNullable(httpapiTrendingTickersListAPIResponse);
            return this;
        }

        /**
         * OK
         */
        public Builder httpapiTrendingTickersListAPIResponse(Optional<? extends HttpapiTrendingTickersListAPIResponse> httpapiTrendingTickersListAPIResponse) {
            Utils.checkNotNull(httpapiTrendingTickersListAPIResponse, "httpapiTrendingTickersListAPIResponse");
            this.httpapiTrendingTickersListAPIResponse = httpapiTrendingTickersListAPIResponse;
            return this;
        }
        
        public GetTickerTrendListDataResponse build() {
            return new GetTickerTrendListDataResponse(
                contentType,
                statusCode,
                rawResponse,
                httpapiTrendingTickersListAPIResponse);
        }
    }
}

