/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.benzinga.bzclient.models.operations;


import com.benzinga.bzclient.models.components.HttpapiTickerTrendAPIResponse;
import com.benzinga.bzclient.utils.Response;
import com.benzinga.bzclient.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;


public class GetTickerTrendDataResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * OK
     */
    private Optional<? extends HttpapiTickerTrendAPIResponse> httpapiTickerTrendAPIResponse;

    @JsonCreator
    public GetTickerTrendDataResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends HttpapiTickerTrendAPIResponse> httpapiTickerTrendAPIResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(httpapiTickerTrendAPIResponse, "httpapiTickerTrendAPIResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.httpapiTickerTrendAPIResponse = httpapiTickerTrendAPIResponse;
    }
    
    public GetTickerTrendDataResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * OK
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<HttpapiTickerTrendAPIResponse> httpapiTickerTrendAPIResponse() {
        return (Optional<HttpapiTickerTrendAPIResponse>) httpapiTickerTrendAPIResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public GetTickerTrendDataResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GetTickerTrendDataResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetTickerTrendDataResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * OK
     */
    public GetTickerTrendDataResponse withHttpapiTickerTrendAPIResponse(HttpapiTickerTrendAPIResponse httpapiTickerTrendAPIResponse) {
        Utils.checkNotNull(httpapiTickerTrendAPIResponse, "httpapiTickerTrendAPIResponse");
        this.httpapiTickerTrendAPIResponse = Optional.ofNullable(httpapiTickerTrendAPIResponse);
        return this;
    }

    /**
     * OK
     */
    public GetTickerTrendDataResponse withHttpapiTickerTrendAPIResponse(Optional<? extends HttpapiTickerTrendAPIResponse> httpapiTickerTrendAPIResponse) {
        Utils.checkNotNull(httpapiTickerTrendAPIResponse, "httpapiTickerTrendAPIResponse");
        this.httpapiTickerTrendAPIResponse = httpapiTickerTrendAPIResponse;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetTickerTrendDataResponse other = (GetTickerTrendDataResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.httpapiTickerTrendAPIResponse, other.httpapiTickerTrendAPIResponse);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            httpapiTickerTrendAPIResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetTickerTrendDataResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "httpapiTickerTrendAPIResponse", httpapiTickerTrendAPIResponse);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends HttpapiTickerTrendAPIResponse> httpapiTickerTrendAPIResponse = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * OK
         */
        public Builder httpapiTickerTrendAPIResponse(HttpapiTickerTrendAPIResponse httpapiTickerTrendAPIResponse) {
            Utils.checkNotNull(httpapiTickerTrendAPIResponse, "httpapiTickerTrendAPIResponse");
            this.httpapiTickerTrendAPIResponse = Optional.ofNullable(httpapiTickerTrendAPIResponse);
            return this;
        }

        /**
         * OK
         */
        public Builder httpapiTickerTrendAPIResponse(Optional<? extends HttpapiTickerTrendAPIResponse> httpapiTickerTrendAPIResponse) {
            Utils.checkNotNull(httpapiTickerTrendAPIResponse, "httpapiTickerTrendAPIResponse");
            this.httpapiTickerTrendAPIResponse = httpapiTickerTrendAPIResponse;
            return this;
        }
        
        public GetTickerTrendDataResponse build() {
            return new GetTickerTrendDataResponse(
                contentType,
                statusCode,
                rawResponse,
                httpapiTickerTrendAPIResponse);
        }
    }
}

