/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.benzinga.bzclient.models.components;


import com.benzinga.bzclient.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;


public class ModelsDividendJSON {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dividends")
    private Optional<? extends List<Map<String, Object>>> dividends;

    @JsonCreator
    public ModelsDividendJSON(
            @JsonProperty("dividends") Optional<? extends List<Map<String, Object>>> dividends) {
        Utils.checkNotNull(dividends, "dividends");
        this.dividends = dividends;
    }
    
    public ModelsDividendJSON() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<Map<String, Object>>> dividends() {
        return (Optional<List<Map<String, Object>>>) dividends;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public ModelsDividendJSON withDividends(List<Map<String, Object>> dividends) {
        Utils.checkNotNull(dividends, "dividends");
        this.dividends = Optional.ofNullable(dividends);
        return this;
    }

    public ModelsDividendJSON withDividends(Optional<? extends List<Map<String, Object>>> dividends) {
        Utils.checkNotNull(dividends, "dividends");
        this.dividends = dividends;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ModelsDividendJSON other = (ModelsDividendJSON) o;
        return 
            Objects.deepEquals(this.dividends, other.dividends);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            dividends);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ModelsDividendJSON.class,
                "dividends", dividends);
    }
    
    public final static class Builder {
 
        private Optional<? extends List<Map<String, Object>>> dividends = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder dividends(List<Map<String, Object>> dividends) {
            Utils.checkNotNull(dividends, "dividends");
            this.dividends = Optional.ofNullable(dividends);
            return this;
        }

        public Builder dividends(Optional<? extends List<Map<String, Object>>> dividends) {
            Utils.checkNotNull(dividends, "dividends");
            this.dividends = dividends;
            return this;
        }
        
        public ModelsDividendJSON build() {
            return new ModelsDividendJSON(
                dividends);
        }
    }
}

