/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.bzclient.bzclient.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * GetInsiderTransactionOwnerQueryParamChamber - Chamber
 */
public enum GetInsiderTransactionOwnerQueryParamChamber {
    HOUSE("House"),
    SENATE("Senate");

    @JsonValue
    private final String value;

    private GetInsiderTransactionOwnerQueryParamChamber(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<GetInsiderTransactionOwnerQueryParamChamber> fromValue(String value) {
        for (GetInsiderTransactionOwnerQueryParamChamber o: GetInsiderTransactionOwnerQueryParamChamber.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
