/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.bzclient.bzclient.models.operations;

import io.bzclient.bzclient.utils.Options;
import io.bzclient.bzclient.utils.RetryConfig;
import io.bzclient.bzclient.utils.Utils;
import java.util.Optional;

public class GetOfferingsRequestBuilder {

    private GetOfferingsRequest request;
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKMethodInterfaces.MethodCallGetOfferings sdk;

    public GetOfferingsRequestBuilder(SDKMethodInterfaces.MethodCallGetOfferings sdk) {
        this.sdk = sdk;
    }

    public GetOfferingsRequestBuilder request(GetOfferingsRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }
                
    public GetOfferingsRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public GetOfferingsRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }

    public GetOfferingsResponse call() throws Exception {
        Optional<Options> options = Optional.of(Options.builder()
                                                    .retryConfig(retryConfig)
                                                    .build());
        return sdk.get(
            request,
            options);
    }
}
