workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Benzinga APIs:
        inputs:
            - location: openapi.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/benzinga/benzinga/benzinga-ap-is
targets:
    bzclient:
        target: java
        source: Benzinga APIs
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/benzinga/benzinga/benzinga-ap-is-java-code-samples
            blocking: false
