/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.benzinga.BZClient.models.components;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.benzinga.BZClient.utils.Utils;


public class ModelsInsiderTransactionFilingJSON {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    private Optional<? extends List<Map<String, Object>>> data;

    @JsonCreator
    public ModelsInsiderTransactionFilingJSON(
            @JsonProperty("data") Optional<? extends List<Map<String, Object>>> data) {
        Utils.checkNotNull(data, "data");
        this.data = data;
    }
    
    public ModelsInsiderTransactionFilingJSON() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<Map<String, Object>>> data() {
        return (Optional<List<Map<String, Object>>>) data;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public ModelsInsiderTransactionFilingJSON withData(List<Map<String, Object>> data) {
        Utils.checkNotNull(data, "data");
        this.data = Optional.ofNullable(data);
        return this;
    }

    public ModelsInsiderTransactionFilingJSON withData(Optional<? extends List<Map<String, Object>>> data) {
        Utils.checkNotNull(data, "data");
        this.data = data;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ModelsInsiderTransactionFilingJSON other = (ModelsInsiderTransactionFilingJSON) o;
        return 
            Objects.deepEquals(this.data, other.data);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            data);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ModelsInsiderTransactionFilingJSON.class,
                "data", data);
    }
    
    public final static class Builder {
 
        private Optional<? extends List<Map<String, Object>>> data = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder data(List<Map<String, Object>> data) {
            Utils.checkNotNull(data, "data");
            this.data = Optional.ofNullable(data);
            return this;
        }

        public Builder data(Optional<? extends List<Map<String, Object>>> data) {
            Utils.checkNotNull(data, "data");
            this.data = data;
            return this;
        }
        
        public ModelsInsiderTransactionFilingJSON build() {
            return new ModelsInsiderTransactionFilingJSON(
                data);
        }
    }
}

