/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.benzinga.BZClient.models.components;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.benzinga.BZClient.utils.Utils;


public class ModelsGuidanceJSON {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("guidance")
    private Optional<? extends List<Map<String, Object>>> guidance;

    @JsonCreator
    public ModelsGuidanceJSON(
            @JsonProperty("guidance") Optional<? extends List<Map<String, Object>>> guidance) {
        Utils.checkNotNull(guidance, "guidance");
        this.guidance = guidance;
    }
    
    public ModelsGuidanceJSON() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<Map<String, Object>>> guidance() {
        return (Optional<List<Map<String, Object>>>) guidance;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public ModelsGuidanceJSON withGuidance(List<Map<String, Object>> guidance) {
        Utils.checkNotNull(guidance, "guidance");
        this.guidance = Optional.ofNullable(guidance);
        return this;
    }

    public ModelsGuidanceJSON withGuidance(Optional<? extends List<Map<String, Object>>> guidance) {
        Utils.checkNotNull(guidance, "guidance");
        this.guidance = guidance;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ModelsGuidanceJSON other = (ModelsGuidanceJSON) o;
        return 
            Objects.deepEquals(this.guidance, other.guidance);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            guidance);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ModelsGuidanceJSON.class,
                "guidance", guidance);
    }
    
    public final static class Builder {
 
        private Optional<? extends List<Map<String, Object>>> guidance = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder guidance(List<Map<String, Object>> guidance) {
            Utils.checkNotNull(guidance, "guidance");
            this.guidance = Optional.ofNullable(guidance);
            return this;
        }

        public Builder guidance(Optional<? extends List<Map<String, Object>>> guidance) {
            Utils.checkNotNull(guidance, "guidance");
            this.guidance = guidance;
            return this;
        }
        
        public ModelsGuidanceJSON build() {
            return new ModelsGuidanceJSON(
                guidance);
        }
    }
}

