/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.bzclient.bzclient.models.components;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.bzclient.bzclient.utils.Utils;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;


public class ModelsSplitJSON {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("splits")
    private Optional<? extends List<Map<String, Object>>> splits;

    @JsonCreator
    public ModelsSplitJSON(
            @JsonProperty("splits") Optional<? extends List<Map<String, Object>>> splits) {
        Utils.checkNotNull(splits, "splits");
        this.splits = splits;
    }
    
    public ModelsSplitJSON() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<Map<String, Object>>> splits() {
        return (Optional<List<Map<String, Object>>>) splits;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public ModelsSplitJSON withSplits(List<Map<String, Object>> splits) {
        Utils.checkNotNull(splits, "splits");
        this.splits = Optional.ofNullable(splits);
        return this;
    }

    public ModelsSplitJSON withSplits(Optional<? extends List<Map<String, Object>>> splits) {
        Utils.checkNotNull(splits, "splits");
        this.splits = splits;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ModelsSplitJSON other = (ModelsSplitJSON) o;
        return 
            Objects.deepEquals(this.splits, other.splits);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            splits);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ModelsSplitJSON.class,
                "splits", splits);
    }
    
    public final static class Builder {
 
        private Optional<? extends List<Map<String, Object>>> splits = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder splits(List<Map<String, Object>> splits) {
            Utils.checkNotNull(splits, "splits");
            this.splits = Optional.ofNullable(splits);
            return this;
        }

        public Builder splits(Optional<? extends List<Map<String, Object>>> splits) {
            Utils.checkNotNull(splits, "splits");
            this.splits = splits;
            return this;
        }
        
        public ModelsSplitJSON build() {
            return new ModelsSplitJSON(
                splits);
        }
    }
}

