/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.bzclient.bzclient.models.components;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.bzclient.bzclient.utils.Utils;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;


public class ModelsIPOJSON {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ipos")
    private Optional<? extends List<Map<String, Object>>> ipos;

    @JsonCreator
    public ModelsIPOJSON(
            @JsonProperty("ipos") Optional<? extends List<Map<String, Object>>> ipos) {
        Utils.checkNotNull(ipos, "ipos");
        this.ipos = ipos;
    }
    
    public ModelsIPOJSON() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<Map<String, Object>>> ipos() {
        return (Optional<List<Map<String, Object>>>) ipos;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public ModelsIPOJSON withIpos(List<Map<String, Object>> ipos) {
        Utils.checkNotNull(ipos, "ipos");
        this.ipos = Optional.ofNullable(ipos);
        return this;
    }

    public ModelsIPOJSON withIpos(Optional<? extends List<Map<String, Object>>> ipos) {
        Utils.checkNotNull(ipos, "ipos");
        this.ipos = ipos;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ModelsIPOJSON other = (ModelsIPOJSON) o;
        return 
            Objects.deepEquals(this.ipos, other.ipos);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            ipos);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ModelsIPOJSON.class,
                "ipos", ipos);
    }
    
    public final static class Builder {
 
        private Optional<? extends List<Map<String, Object>>> ipos = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder ipos(List<Map<String, Object>> ipos) {
            Utils.checkNotNull(ipos, "ipos");
            this.ipos = Optional.ofNullable(ipos);
            return this;
        }

        public Builder ipos(Optional<? extends List<Map<String, Object>>> ipos) {
            Utils.checkNotNull(ipos, "ipos");
            this.ipos = ipos;
            return this;
        }
        
        public ModelsIPOJSON build() {
            return new ModelsIPOJSON(
                ipos);
        }
    }
}

