/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.bzclient.bzclient.models.components;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.bzclient.bzclient.utils.Utils;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;


public class ModelsEarningJSON {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("earnings")
    private Optional<? extends List<Map<String, Object>>> earnings;

    @JsonCreator
    public ModelsEarningJSON(
            @JsonProperty("earnings") Optional<? extends List<Map<String, Object>>> earnings) {
        Utils.checkNotNull(earnings, "earnings");
        this.earnings = earnings;
    }
    
    public ModelsEarningJSON() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<Map<String, Object>>> earnings() {
        return (Optional<List<Map<String, Object>>>) earnings;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public ModelsEarningJSON withEarnings(List<Map<String, Object>> earnings) {
        Utils.checkNotNull(earnings, "earnings");
        this.earnings = Optional.ofNullable(earnings);
        return this;
    }

    public ModelsEarningJSON withEarnings(Optional<? extends List<Map<String, Object>>> earnings) {
        Utils.checkNotNull(earnings, "earnings");
        this.earnings = earnings;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ModelsEarningJSON other = (ModelsEarningJSON) o;
        return 
            Objects.deepEquals(this.earnings, other.earnings);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            earnings);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ModelsEarningJSON.class,
                "earnings", earnings);
    }
    
    public final static class Builder {
 
        private Optional<? extends List<Map<String, Object>>> earnings = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder earnings(List<Map<String, Object>> earnings) {
            Utils.checkNotNull(earnings, "earnings");
            this.earnings = Optional.ofNullable(earnings);
            return this;
        }

        public Builder earnings(Optional<? extends List<Map<String, Object>>> earnings) {
            Utils.checkNotNull(earnings, "earnings");
            this.earnings = earnings;
            return this;
        }
        
        public ModelsEarningJSON build() {
            return new ModelsEarningJSON(
                earnings);
        }
    }
}

